name: Build and deploy container app to Azure Web App - ManyToManyStudentCourse

on:
  push:
    branches:
      - master
      
env:
  REGISTRY: kabsoftacr.azurecr.io
  IMAGE_NAME: manytomanystucoimage
  APP_NAME: ManyToManyStudentCourse
  DOTNET_VERSION: '6.0.x'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AzureAppService_ContainerUsername_31cc6eb9a8d14d08b6e3d24bef4b7aee }}
          password: ${{ secrets.AzureAppService_ContainerPassword_8784f407d7134e539119f2cb598b6da3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.AzureAppService_ContainerUsername_31cc6eb9a8d14d08b6e3d24bef4b7aee }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.APP_NAME }}
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_30463ef4b5f3403e91ee3b0febc1f442 }}
            images: ${{ env.REGISTRY }}/${{ secrets.AzureAppService_ContainerUsername_31cc6eb9a8d14d08b6e3d24bef4b7aee }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'