name: .NET ManyToManyStudentCourse

on:
  push:
    branches: [ "*"]
  pull_request:
    branches: [ "master" ]

env: 
  NETCORE_VERSION: '6.0.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format
  
    - name: Check Format
      run: dotnet-format ManyToManyStudentCourse.sln --check

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal